#!/usr/bin/env sh

# LIBRARY IMPORTS
. ./lib/utilities/colors  # Both are used to make the installer pretty
. ./lib/utilities/print

# FILE DEFINED CONSTANTS
AUTH_FILE="/etc/warden/auth"


# Install the Warden files and configurations
InstallWarden () {
    
    printf "\n"
    print "${YELLOW}[-] INSTALL A SERVICE ACCOUNT"
    print "${RED}[ ] CREATE FILES/DIRECTORIES"
    print "${RED}[ ] INSTALL WARDEN FILES"
    print "${RED}[ ] START SERVICES"
    print "${RED}[ ] CLEANUP"
    printf "%s\n" "[0/5][-----]"

    # INSTALLATION STEP 1 -> SERVICE ACCOUNT
    # Generate a service account for Blueshell 
    # orchestration, maintenance, and administration
    useradd -r -d / -s /sbin/false -c "Warden Administration User" warden
    groupadd warden-admin
    usermod -aG warden-admin warden
    passwd -l warden 1> /dev/null

    # SERVICE ACCOUNT VALIDATION
    if ! getent passwd warden > /dev/null 2>&1;
    then
        printCritical "Failed to install Blueshell: Could not create service user account..."
        return 1
    fi

    printf "\n"
    printf "\e[6A\e[J"
    print "${GREEN}[✓] INSTALL A SERVICE ACCOUNT"
    print "${YELLOW}[-] CREATE FILES/DIRECTORIES"
    print "${RED}[ ] INSTALL WARDEN"
    print "${RED}[ ] START SERVICES"
    print "${RED}[ ] CLEANUP"
    printf "%s" -n "[1/5][=----]"
    

    # ==========

    # INSTALLATION STEP 2 -> FILES AND DIRECTORIES
    # Generate file paths for configurations and logging 
    # and manage access with ownership

    # LOGGING PATH
    mkdir /var/log/warden
    chown warden /var/log/warden
    
    # WORKING FILE PATH
    mkdir /var/lib/warden
    chown warden /var/lib/warden

    # CONFIG FILE PATH
    mkdir /etc/warden
    chown warden /etc/warden

    # INSTALL PATH
    mkdir /opt/warden
    chown -R warden /opt/warden

    # RUN PATH
    mkdir /run/warden
    mkdir /run/warden/wlog
    chown -R warden /run/warden

    # FILE PATH VALIDATION INSTALLATION
    if [ ! -e /var/log/warden ] || 
       [ ! -e /var/lib/warden ] || 
       [ ! -e /etc/warden ] ||
       [ ! -e /run/warden ] ||
       [ ! -e /opt/warden ];  
    then 
        printCritical "Failed to install Warden: Could not validate installation paths..."
        return 1
    fi

    printf "\e[6A\e[J"
    print "${GREEN}[✓] INSTALL A SERVICE ACCOUNT"
    print "${GREEN}[✓] CREATE FILES/DIRECTORIES"
    print "${YELLOW}[-] INSTALL WARDEN"
    print "${RED}[ ] START SERVICES"
    print "${RED}[ ] CLEANUP"
    printf "%s""[2/5][==---]"

    # ==========

    # INSTALLATION STEP 3 -> INSTALL BLUESHELL SCRIPTS LOCALLY - /opt/blueshell
    # Downloads the installation package from github -> online
    # Extracts local archive for files -> offline
    # Moves a copy of downloaded files and installer script within the install path

    # MOVE LIBRARY AND CONFIG FILES TO DIRS
    cp -r ./etc/* /etc/warden  1>/dev/null
    cp -r ./lib/* /var/lib/warden  1>/dev/null
    
    # MOVE SCRIPTS TO /USR/BIN
    cp ./src/wsh /usr/bin 1>/dev/null
    cp ./src/wcfg /usr/bin 1>/dev/null
    cp ./src/log/wlog /usr/bin 1>/dev/null

    # MOVE HELPER TO /OPT DIR
    cp -r ./.install/uninstall /opt/warden 1>/dev/null
    
    # MOVE SERVICE FILE FOR SYSTEMD
    cp ./src/log/wlog.service /etc/systemd/system  1>/dev/null
    
    # MAKE A COPY OF THE DATA AND MOVE IT TO /OPT FOR HELPER
    zip -r /opt/warden/.data ./ 1>/dev/null
    
    # ADD WSH TO VALID SHELLS
    printf "%s\n" "/bin/wsh" | tee -a /etc/shells
    printf "%s\n" "/usr/bin/wsh" | tee -a /etc/shells

    printf "\e[6A\e[J"
    print "${GREEN}[✓] INSTALL A SERVICE ACCOUNT"
    print "${GREEN}[✓] CREATE FILES/DIRECTORIES"
    print "${GREEN}[✓] INSTALL WARDEN"
    print "${YELLOW}[-] START SERVICES"
    print "${RED}[ ] CLEANUP"
    printf "%s" "[3/5][===--]"
    
    # ==========

    # INSTALLATION STEP 4 -> START SYSTEM LOGGING SERVICE

    systemctl enable wlog.service
    systemctl start wlog.service
    
    printf "\e[6A\e[J"
    print "${GREEN}[✓] INSTALL A SERVICE ACCOUNT"
    print "${GREEN}[✓] CREATE FILES/DIRECTORIES"
    print "${GREEN}[✓] INSTALL WARDEN"
    print "${GREEN}[✓] START SERVICES"
    print "${YELLOW}[-] CLEANUP"
    printf "%s" "[4/5][====-]"


    # ==========

    # INSTALLATION STEP 5 -> INSTALLER CLEANUP

    CleanUpInstaller

    printf "\e[6A\e[J"
    print "${GREEN}[✓] INSTALL A SERVICE ACCOUNT"
    print "${GREEN}[✓] CREATE FILES/DIRECTORIES"
    print "${GREEN}[✓] INSTALL WARDEN"
    print "${GREEN}[✓] START SERVICES"
    print "${GREEN}[✓] CLEANUP"
    printf "%s\n" "[5/5][=====]"
    printf "\n"

}


# Removes all install paths and file modifications from the system
RemoveWarden () {

    rm -rf /etc/systemd/system/wlog.service
    systemctl disable wlog.service 2> /dev/null
    systemctl stop wlog.service 2> /dev/null

    # REMOVE BLUESHELL ADMINISTRATION USER
    userdel warden
    groupdel warden-admin

    # CLEANUP INSTALL PATHS
    rm -rf /var/log/warden
    rm -rf /var/lib/warden
    rm -rf /etc/warden
    rm -rf /opt/warden
    rm -rf /run/warden

    rm -rf /usr/bin/wsh
    rm -rf /usr/bin/wlog
    rm -rf /usr/bin/wcfg
    
    sed -i '\|/bin/wsh|d' /etc/shells
    sed -i '\|/usr/bin/wsh|d' /etc/shells

}


# The function call for the initial password setup
# for configuration and breakout
PasswordSetup () {

    
    stty -echo
    printf "%s" "New Password: "
    read -r newPass; printf "\n"

    printf "%s" "Confirm Password: "
    read -r confPass ; printf "\n"
    stty echo
    
    if [ $newPass == $confPass ]; then
        printf "%s" "$newPass" | sha256sum > "$AUTH_FILE"
        printf "%s\n" "Password Setup"
    else
        printf "%s\n" "Passwords do not match"
        PasswordSetup
    fi
}


# Check if user is root
if (( $EUID != 0 )); 
then
    printf "%s\n" "Permission denied: This installer requires root privileges"
else
    cat ./.install/InstallBanner
    printf "\n"

    # check if there exists traces of the tooling
    if [ -e "/usr/bin/wsh" ] ||
       [ -e "/usr/bin/wcfg" ] ||
       [ -e "/usr/bin/wlog" ] || 
       getent passwd warden > /dev/null 2>&1; 
    then
        read -p "Would you like to remove Warden from your system? (Y/N): " input
        case "$input" in
            [Yy]*)
                if RemoveWarden;
                then 
                    printf "%s\n"  "Warden removed successfully from your system!"
                    exit 0
                fi
            ;;
            [Nn]*)
                printf "%s\n" "Goodbye!"
                exit 0
            ;;
        esac

    else
        read -p "Would you like to install Warden? (Y/N): " input
        case "$input" in
            [Yy]* )
                if InstallWarden;
                then 
                    printf "%s\n" "Please Create a password for the shell breakout"
                    if PasswordSetup;
                    then

                        # FIX - NOT FINAL
                        # Fixes permission issues -> contrain to warden-admin group
                        chgrp -R warden-admin /etc/warden
                        chmod -R 775 /etc/warden
                        chmod -R 755 /var/lib/warden

                        printf "\n%s\n" "WARDEN has been installed successfully!"
                        printf "\n%s\n" "For more information, please visit:"
                        printf "%s\n" "  https://github.com/SYNT4X1/Warden.git"
                        exit 0
                    fi
                else
                    RemoveWarden
                    exit 0
                fi
            ;;
            [Nn]* )
                printf "%s\n" "Goodbye!"
                exit 0
            ;;
        esac
    fi
fi