#!/usr/bin/env sh

# DESCRIPTION
# This defines the authentication library for the 
# Warden shell jail

# LIBRARY IMPORTS
. /etc/warden/warden.conf
. /var/lib/warden/utilities/log

# FILE CONSTANTS
SYS_LOCK="/etc/warden/sys.lock"
USR_LOCK="/etc/warden/user.lock"
ADR_LOCK="/etc/warden/addr.lock"
AUTH_FILE="/etc/warden/auth"


# Checks if a value provided for a warden lock
# file contains a separately provided value for
# locking purposes
checkLock (){

    # Check the system lock
    if [ -f $SYS_LOCK ]; 
    then
        return 0
    fi
    
    # Check if user is locked by name
    if [ -f $USR_LOCK ]; 
    then
        while IFS=":" read -r LOCK_SET LOCK_VALUE || [ -n "$LOCK_SET" ];
        do
            if [ "$LOCK_SET" = "1" ] && [ "$LOCK_VALUE" = "$1" ]
            then
                return 0 # locked (lock found)
            fi
        done < "$USR_LOCK"
    fi

    # Check if the $SSH_CONNECTION env var is set and
    # check if it's locked by name
    if [ -f $ADR_LOCK ] && [ -n "$SSH_CONNECTION" ]; 
        then
        while IFS=":" read -r LOCK_SET LOCK_VALUE || [ -n "$LOCK_SET" ];
        do
            if [ "$LOCK_SET" = "1" ] && [ "$LOCK_VALUE" = "$SSH_CONNECTION" ];
            then
                return 0
            fi
        done < "$ADR_LOCK"
    fi

    return 1 # not locked
    
}


# Perform a hashed string compare of the 
# stored password and supplied string
PasswordAuth () {

    if [ "$(printf "%s" "$1" | sha256sum)" == "$(head -n 1 $AUTH_FILE | grep - )" ]; 
    then
        return 0
    else
        return 1
    fi
}


# An initial password prompt for authenticating 
# changes to the password
AuthPrompt () {

    try=0

    while [ "$try" -lt "$PASSWORD_TRYS" ];
    do

        try=$((try + 1))
    
        stty -echo
        echo -n "Password: "
		read -r password_input; echo
		stty echo

        if PasswordAuth "$password_input"; then
            return 0
        else
            echo "incorrect password..."
        fi
    done
    return 1

}


# write supplied string to the authencation file
# and log the event with warden log handler
UpdatePassword () {

    if printf "%s" "$newPass" | sha256sum > "$AUTH_FILE";
    then
        Log "[PASS][$(date -u +"%Y%m%d-%H:%M:%S")] Password for breakout command has been updated"
        return 0
    else
        return 1
    fi

}


# Prompt used to create a new password
# performs a few validation checks for QOL
NewPasswordPrompt () {

    passwordUpdated=false

    while ! $passwordUpdated;
    do
        stty -echo
        printf "%s" "New Password: "
        read -s -r newPass; echo
        printf "%s" "Confirm Password: "
        read -s -r confPass; echo
        stty echo
        
        if [ "$newPass" == "$confPass" ]; then
            if UpdatePassword $newPass; then
                passwordUpdated=true
                echo "Password Updated"
                return 0
            else
                return 1
            fi
        else
            echo "Passwords do not match"
        fi
    done

}