#!/usr/bin/env sh

# DESCRIPTION
# A collection of useful ansi escape codes
# for displaying colors to the tty

RESET_COLOR="\033[0m"

RED="\033[0;31m"
YELLOW="\033[0;33m"
GREEN="\033[0;32m"
BRIGHT_BLUE="\033[0;94m"
CYAN="\033[0;36m"