#!/usr/bin/env sh

# DESCRIPTION
# This libaray function that pushes log data 
# from $1 to the fifo sink made for the warden
# logging daemon

# FILE CONSTANTS
LOG_SINK="/run/warden/wlog/sink"


# Log the value of $1 to warden logs
Log () {
    if [ -p "$LOG_SINK" ];
    then
        printf "%s\n" "$1" > "$LOG_SINK"
        return 0
    else
        return 1
    fi

}