#!/usr/bin/env sh

# DESCRIPTION
# a simple print command used to clean up code and allow 
# the printed of formatted colored text to the tty

# USAGE (single color): print "${<COLOR>}<TEXT>"

# USAGE (multi color): print "${<COLOR1>}<TEXT1> ${<COLOR2>}<TEXT2>"

print () { 
    printf "%s\n" "$1 ${RESET_COLOR}" 
}