#!/usr/bin/env sh

# LIBRARY IMPORTS
. /var/lib/warden/utilities/auth  # Used for password authentication/administration


# Print script help banner
help () {
	cat "/var/lib/warden/banners/wcfg.banner"	
}


# Prints script usage banner for help
# banner and on failed command usage
usage () {
    printf "%s\n" "usage: wcfg --change-password"
	printf "%s\n" "usage: wcfg --l ip 127.0.0.1"
	printf "%s\n" "usage: wcfg --lock user username"

	printf "\n%s\n" "usage: wcfg --lock-enable ip 127.0.0.1"
	printf "%s\n" "usage: wcfg -le user username"

	printf "\n%s\n" "usage: wcfg --lock-disable ip 127.0.0.1"
	printf "%s\n" "usage: wcfg --ld user username"
}


# Check if the user is in the warden-admin group
if id -Gn "$USER" | grep -qw "warden-admin"; 
then
    case "$1" in 
	
	"-ls"|"--list-locks")
		printf "%s\n" "- USER LOCKS -"
		while IFS=":" read -r LOCK_SET LOCK_VALUE || [ -n "$LOCK_SET" ];
		do
			case "$LOCK_SET" in
			"1")
				printf "LOCKED\t\t\t%s\n" "$LOCK_VALUE"
				;;
			"0")
				printf "UNLOCKED\t\t%s\n" "$LOCK_VALUE"
				;;
    		esac
		done < "$USR_LOCK"
		
		printf "\n%s" "- ADDRESS LOCKS -"
		while IFS=":" read LOCK_SET LOCK_VALUE || [ -n "$LOCK_SET" ];
		do
			case "$LOCK_SET" in
			"1")
				printf "LOCKED\t\t\t%s\n" "$LOCK_VALUE"
				;;
			"0")
				printf "UNLOCKED\t\t%s\n" "$LOCK_VALUE"
				;;
    		esac
		done < "$ADR_LOCK"
	;;

	"-l"|"--lock")
		if ! [ $# -eq 3 ];
		then
			usage
		fi

		case $2 in
		"ip"|"IP")
			if ! grep -q "1:$3" $ADR_LOCK && ! grep -q "0:$3" $ADR_LOCK; 
			then
				printf "%s\n" "1:$3" >> $ADR_LOCK
			else
				printf "%s\n" "Lock already present"
			fi
		;;
		"user"|"USER")
			if ! grep -q "1:$3" $USR_LOCK && ! grep -q "0:$3" $USR_LOCK; 
			then
				printf "%s\n" "1:$3" >> $USR_LOCK
			else
				printf "%s\n" "Lock already present"
			fi
		;;
		esac
	;;
	
	"-le"|"--lock-enable")
		case $2 in
		"ip"|"IP")
			sed -i "s/0:$3/1:$3/" $ADR_LOCK
		;;
		"user"|"USER")
			sed -i "s/0:$3/1:$3/" $USR_LOCK
		;;
		esac
		
	;;

	"-ld"|"--lock-disable")
		case $2 in
		"ip"|"IP")
			sed -i "s/1:$3/0:$3/" $ADR_LOCK
		;;
		"user"|"USER")
			sed -i "s/1:$3/0:$3/" $USR_LOCK
		;;
		esac
	;;

	"-p"|"--change-password")
		if AuthPrompt;
		then
			NewPasswordPrompt
		else
			printf "%s\n" "Password data unchanged..."
		fi
	;;

	"-h"|"--help")
		help
	;;

	"--uninstall")
		/usr/bin/env sh /opt/warden/uninstall
	;;
	"-sl"|"--syslock")
		if ! [ $# -eq 2 ];
		then
			usage
		fi

		case $2 in 
		"enable")
			touch /etc/warden/sys.lock
		;;
		
		"disable")
			rm /etc/warden/sys.lock
		;;

		"status")
			if [ -f $SYS_LOCK ];
			then
				printf "%s\n" "locked"
				exit 0
			else 
				printf "%s\n" "not locked"
				exit 1
			fi
		;;
		esac
	
	;;
	*)
		usage
	;;
	esac
else
    printf "%s\n" "wcfg: Permission Denied"
	exit 1
fi
